services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: munchspace-api
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/munchspace
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: >
      sh -c "npm install && npx prisma migrate deploy && npm run start:dev"


  postgres:
    image: postgres:16-alpine
    container_name: munchspace-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: munchspace
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d munchspace"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    container_name: munchspace-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:latest
  #   container_name: munchspace-otel-collector
  #   command: ["--config=/etc/otelcol/otel-collector.yaml"]
  #   volumes:
  #     - ./docker/otel/otel-collector.yaml:/etc/otelcol/otel-collector.yaml
  #   ports:
  #     - "4317:4317"
  #     - "4318:4318"

volumes:
  pg_data:
  node_modules:
