services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/munchspace
    depends_on:
      postgres:
        condition: service_healthy
      # redis:
      #   condition: service_started
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate dev &&
             npm run start:dev"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./prisma
          target: /app/prisma
        - action: rebuild
          path: package.json

  postgres:
    image: postgres:16-alpine
    container_name: munchspace-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: munchspace
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d munchspace"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: munchspace-pgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@munchspace.io
      PGADMIN_DEFAULT_PASSWORD: Munch@Space123
    depends_on:
      - postgres


  # redis:
  #   image: redis:7-alpine
  #   container_name: munchspace-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"

volumes:
  pg_data:
