services:
  api:
    image: munchspace-api
    environment:
      - DATABASE_URL: postgresql://postgres:postgres@postgres:5432/munchspace
    container_name: munchspace-api
    restart: unless-stopped
    ports:
      - "3000:3000"
